### ISSUE TITLE
No repetition impl for HashSet

### ISSUE THREAD

**Issue by martijnberger** [dtolnay/quote#144]
This code seems to work fine with syn 0.15.x and not with 1.0.x

```rust
let mut frameworks: HashSet<std::string::String> = HashSet::new();
frameworks.insert(format!("Foundation"));

let attr: syn::Attribute = parse_quote!(
    #[cfg(all(#(feature = #frameworks),*))]
);
```

```console
error[E0599]: no method named `quote_into_iter` found for type `std::collections::HashSet<std::string::String>` in the current scope
  --> bin/test.rs:11:32
   |
11 |       let attr: syn::Attribute = parse_quote!(
   |  ________________________________^
12 | |         #[cfg(all(#(feature = #frameworks),*))]
13 | |     );
   | |_____^ method not found in `std::collections::HashSet<std::string::String>`
   |
   = note: the method `quote_into_iter` exists but the following trait bounds were not satisfied:
           `&mut std::collections::HashSet<std::string::String> : syn::export::quote::__rt::ext::RepIteratorExt`
           `&std::collections::HashSet<std::string::String> : syn::export::quote::__rt::ext::RepIteratorExt`
           `std::collections::HashSet<std::string::String> : syn::export::quote::__rt::ext::RepIteratorExt`
           `std::collections::HashSet<std::string::String> : syn::export::quote::__rt::ext::RepToTokensExt`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

I am sorry to not be more helpful but my rust knowledge is not yet to the point where I can figure this one out

**Comment by mystor** [comment]
This is caused by a difference in how repetition is supported between 0.15 and 1.0 `syn` versions. Repetition is supported on BTreeSet, but not on HashSet, as HashSet's ordering is non-deterministic. If you change the map type used for the `feature` repetition to a `BTreeSet`, the code should work again. See #122.

**Comment by dtolnay** [comment]
This is intentional -- HashSet is not a good choice in macros because it is likely to produce different output in different executions, which disrupts caching.
